/* webserver_webserviceServerLib.c
   Generated by gSOAP 2.7.15 from webserver_webservice.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

/** Use this file in your project build instead of the two files webserver_webserviceC.c and webserver_webserviceServer.c. This hides the serializer functions and avoids linking problems when linking multiple clients and servers. */

#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#define SOAP_FMAC3 static
#include "webserver_webserviceC.c"
#include "webserver_webserviceServer.c"

/* End of webserver_webserviceServerLib.c */
