/* webservices_devicewebserviceH.h
   Generated by gSOAP 2.7.15 from webservices_devicewebservice.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef webservices_devicewebserviceH_H
#define webservices_devicewebserviceH_H
#include "webservices_devicewebserviceStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_xsd__byte
#define SOAP_TYPE_xsd__byte (15)
#endif

#define soap_default_xsd__byte(soap, a) soap_default_byte(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_xsd__byte(struct soap*, const char*, char *, const char*);

#define soap_write_xsd__byte(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__byte(soap, data), 0) || soap_put_xsd__byte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__byte(struct soap*, const char *, const char*, const char*);

#define soap_read_xsd__byte(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__byte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_xsd__byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#define soap_write_byte(soap, data) ( soap_begin_send(soap) || (soap_serialize_byte(soap, data), 0) || soap_put_byte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_ns4__char
#define SOAP_TYPE_ns4__char (20)
#endif

#define soap_default_ns4__char(soap, a) soap_default_int(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__char(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_ns4__char(struct soap*, const char*, int *, const char*);

#define soap_write_ns4__char(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns4__char(soap, data), 0) || soap_put_ns4__char(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__char(struct soap*, const int *, const char*, const char*);

#define soap_read_ns4__char(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__char(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_ns4__char(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#define soap_write_int(soap, data) ( soap_begin_send(soap) || (soap_serialize_int(soap, data), 0) || soap_put_int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_xsd__unsignedByte
#define SOAP_TYPE_xsd__unsignedByte (18)
#endif

#define soap_default_xsd__unsignedByte(soap, a) soap_default_unsignedByte(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_xsd__unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#define soap_write_xsd__unsignedByte(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__unsignedByte(soap, data), 0) || soap_put_xsd__unsignedByte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__unsignedByte(struct soap*, const unsigned char *, const char*, const char*);

#define soap_read_xsd__unsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__unsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_xsd__unsignedByte(struct soap*, unsigned char *, const char*, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#define soap_write_unsignedByte(soap, data) ( soap_begin_send(soap) || (soap_serialize_unsignedByte(soap, data), 0) || soap_put_unsignedByte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);

#define soap_read_unsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#define soap_write_unsignedInt(soap, data) ( soap_begin_send(soap) || (soap_serialize_unsignedInt(soap, data), 0) || soap_put_unsignedInt(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);

#define soap_read_unsignedInt(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedInt(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);

#ifndef SOAP_TYPE_ns3__FaultType1
#define SOAP_TYPE_ns3__FaultType1 (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__FaultType1(struct soap*, enum ns3__FaultType1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__FaultType1(struct soap*, const char*, int, const enum ns3__FaultType1 *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns3__FaultType12s(struct soap*, enum ns3__FaultType1);
SOAP_FMAC3 enum ns3__FaultType1 * SOAP_FMAC4 soap_in_ns3__FaultType1(struct soap*, const char*, enum ns3__FaultType1 *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns3__FaultType1(struct soap*, const char*, enum ns3__FaultType1 *);

#define soap_write_ns3__FaultType1(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns3__FaultType1(soap, data), 0) || soap_put_ns3__FaultType1(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__FaultType1(struct soap*, const enum ns3__FaultType1 *, const char*, const char*);

#define soap_read_ns3__FaultType1(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__FaultType1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum ns3__FaultType1 * SOAP_FMAC4 soap_get_ns3__FaultType1(struct soap*, enum ns3__FaultType1 *, const char*, const char*);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, enum xsd__boolean *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum xsd__boolean *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, enum xsd__boolean);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum xsd__boolean *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, enum xsd__boolean *);

#define soap_write_xsd__boolean(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__boolean(soap, data), 0) || soap_put_xsd__boolean(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const enum xsd__boolean *, const char*, const char*);

#define soap_read_xsd__boolean(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__boolean(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum xsd__boolean *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#endif

#ifndef SOAP_TYPE___ns1__Control1
#define SOAP_TYPE___ns1__Control1 (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Control1(struct soap*, struct __ns1__Control1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Control1(struct soap*, const struct __ns1__Control1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Control1(struct soap*, const char*, int, const struct __ns1__Control1 *, const char*);
SOAP_FMAC3 struct __ns1__Control1 * SOAP_FMAC4 soap_in___ns1__Control1(struct soap*, const char*, struct __ns1__Control1 *, const char*);

#define soap_write___ns1__Control1(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__Control1(soap, data), 0) || soap_put___ns1__Control1(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Control1(struct soap*, const struct __ns1__Control1 *, const char*, const char*);

#define soap_read___ns1__Control1(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__Control1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__Control1 * SOAP_FMAC4 soap_get___ns1__Control1(struct soap*, struct __ns1__Control1 *, const char*, const char*);

#ifndef SOAP_TYPE___ns1__Echo1
#define SOAP_TYPE___ns1__Echo1 (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Echo1(struct soap*, struct __ns1__Echo1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Echo1(struct soap*, const struct __ns1__Echo1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Echo1(struct soap*, const char*, int, const struct __ns1__Echo1 *, const char*);
SOAP_FMAC3 struct __ns1__Echo1 * SOAP_FMAC4 soap_in___ns1__Echo1(struct soap*, const char*, struct __ns1__Echo1 *, const char*);

#define soap_write___ns1__Echo1(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__Echo1(soap, data), 0) || soap_put___ns1__Echo1(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Echo1(struct soap*, const struct __ns1__Echo1 *, const char*, const char*);

#define soap_read___ns1__Echo1(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__Echo1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__Echo1 * SOAP_FMAC4 soap_get___ns1__Echo1(struct soap*, struct __ns1__Echo1 *, const char*, const char*);

#ifndef SOAP_TYPE___ns1__Hello1
#define SOAP_TYPE___ns1__Hello1 (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Hello1(struct soap*, struct __ns1__Hello1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Hello1(struct soap*, const struct __ns1__Hello1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Hello1(struct soap*, const char*, int, const struct __ns1__Hello1 *, const char*);
SOAP_FMAC3 struct __ns1__Hello1 * SOAP_FMAC4 soap_in___ns1__Hello1(struct soap*, const char*, struct __ns1__Hello1 *, const char*);

#define soap_write___ns1__Hello1(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__Hello1(soap, data), 0) || soap_put___ns1__Hello1(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Hello1(struct soap*, const struct __ns1__Hello1 *, const char*, const char*);

#define soap_read___ns1__Hello1(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__Hello1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__Hello1 * SOAP_FMAC4 soap_get___ns1__Hello1(struct soap*, struct __ns1__Hello1 *, const char*, const char*);

#ifndef SOAP_TYPE___ns1__GetWsProtocolVersion1
#define SOAP_TYPE___ns1__GetWsProtocolVersion1 (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetWsProtocolVersion1(struct soap*, struct __ns1__GetWsProtocolVersion1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetWsProtocolVersion1(struct soap*, const struct __ns1__GetWsProtocolVersion1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetWsProtocolVersion1(struct soap*, const char*, int, const struct __ns1__GetWsProtocolVersion1 *, const char*);
SOAP_FMAC3 struct __ns1__GetWsProtocolVersion1 * SOAP_FMAC4 soap_in___ns1__GetWsProtocolVersion1(struct soap*, const char*, struct __ns1__GetWsProtocolVersion1 *, const char*);

#define soap_write___ns1__GetWsProtocolVersion1(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__GetWsProtocolVersion1(soap, data), 0) || soap_put___ns1__GetWsProtocolVersion1(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetWsProtocolVersion1(struct soap*, const struct __ns1__GetWsProtocolVersion1 *, const char*, const char*);

#define soap_read___ns1__GetWsProtocolVersion1(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetWsProtocolVersion1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__GetWsProtocolVersion1 * SOAP_FMAC4 soap_get___ns1__GetWsProtocolVersion1(struct soap*, struct __ns1__GetWsProtocolVersion1 *, const char*, const char*);

#ifndef SOAP_TYPE___ns1__Ping1
#define SOAP_TYPE___ns1__Ping1 (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Ping1(struct soap*, struct __ns1__Ping1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Ping1(struct soap*, const struct __ns1__Ping1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Ping1(struct soap*, const char*, int, const struct __ns1__Ping1 *, const char*);
SOAP_FMAC3 struct __ns1__Ping1 * SOAP_FMAC4 soap_in___ns1__Ping1(struct soap*, const char*, struct __ns1__Ping1 *, const char*);

#define soap_write___ns1__Ping1(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__Ping1(soap, data), 0) || soap_put___ns1__Ping1(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Ping1(struct soap*, const struct __ns1__Ping1 *, const char*, const char*);

#define soap_read___ns1__Ping1(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__Ping1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns1__Ping1 * SOAP_FMAC4 soap_get___ns1__Ping1(struct soap*, struct __ns1__Ping1 *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#endif

#ifndef SOAP_TYPE__ns3__Control1Response
#define SOAP_TYPE__ns3__Control1Response (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__Control1Response(struct soap*, struct _ns3__Control1Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__Control1Response(struct soap*, const struct _ns3__Control1Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__Control1Response(struct soap*, const char*, int, const struct _ns3__Control1Response *, const char*);
SOAP_FMAC3 struct _ns3__Control1Response * SOAP_FMAC4 soap_in__ns3__Control1Response(struct soap*, const char*, struct _ns3__Control1Response *, const char*);

#define soap_write__ns3__Control1Response(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns3__Control1Response(soap, data), 0) || soap_put__ns3__Control1Response(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__Control1Response(struct soap*, const struct _ns3__Control1Response *, const char*, const char*);

#define soap_read__ns3__Control1Response(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__Control1Response(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Control1Response * SOAP_FMAC4 soap_get__ns3__Control1Response(struct soap*, struct _ns3__Control1Response *, const char*, const char*);

#ifndef SOAP_TYPE__ns3__Control1
#define SOAP_TYPE__ns3__Control1 (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__Control1(struct soap*, struct _ns3__Control1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__Control1(struct soap*, const struct _ns3__Control1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__Control1(struct soap*, const char*, int, const struct _ns3__Control1 *, const char*);
SOAP_FMAC3 struct _ns3__Control1 * SOAP_FMAC4 soap_in__ns3__Control1(struct soap*, const char*, struct _ns3__Control1 *, const char*);

#define soap_write__ns3__Control1(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns3__Control1(soap, data), 0) || soap_put__ns3__Control1(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__Control1(struct soap*, const struct _ns3__Control1 *, const char*, const char*);

#define soap_read__ns3__Control1(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__Control1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Control1 * SOAP_FMAC4 soap_get__ns3__Control1(struct soap*, struct _ns3__Control1 *, const char*, const char*);

#ifndef SOAP_TYPE__ns3__Echo1Response
#define SOAP_TYPE__ns3__Echo1Response (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__Echo1Response(struct soap*, struct _ns3__Echo1Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__Echo1Response(struct soap*, const struct _ns3__Echo1Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__Echo1Response(struct soap*, const char*, int, const struct _ns3__Echo1Response *, const char*);
SOAP_FMAC3 struct _ns3__Echo1Response * SOAP_FMAC4 soap_in__ns3__Echo1Response(struct soap*, const char*, struct _ns3__Echo1Response *, const char*);

#define soap_write__ns3__Echo1Response(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns3__Echo1Response(soap, data), 0) || soap_put__ns3__Echo1Response(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__Echo1Response(struct soap*, const struct _ns3__Echo1Response *, const char*, const char*);

#define soap_read__ns3__Echo1Response(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__Echo1Response(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Echo1Response * SOAP_FMAC4 soap_get__ns3__Echo1Response(struct soap*, struct _ns3__Echo1Response *, const char*, const char*);

#ifndef SOAP_TYPE__ns3__Echo1
#define SOAP_TYPE__ns3__Echo1 (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__Echo1(struct soap*, struct _ns3__Echo1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__Echo1(struct soap*, const struct _ns3__Echo1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__Echo1(struct soap*, const char*, int, const struct _ns3__Echo1 *, const char*);
SOAP_FMAC3 struct _ns3__Echo1 * SOAP_FMAC4 soap_in__ns3__Echo1(struct soap*, const char*, struct _ns3__Echo1 *, const char*);

#define soap_write__ns3__Echo1(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns3__Echo1(soap, data), 0) || soap_put__ns3__Echo1(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__Echo1(struct soap*, const struct _ns3__Echo1 *, const char*, const char*);

#define soap_read__ns3__Echo1(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__Echo1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Echo1 * SOAP_FMAC4 soap_get__ns3__Echo1(struct soap*, struct _ns3__Echo1 *, const char*, const char*);

#ifndef SOAP_TYPE__ns3__Hello1Response
#define SOAP_TYPE__ns3__Hello1Response (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__Hello1Response(struct soap*, struct _ns3__Hello1Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__Hello1Response(struct soap*, const struct _ns3__Hello1Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__Hello1Response(struct soap*, const char*, int, const struct _ns3__Hello1Response *, const char*);
SOAP_FMAC3 struct _ns3__Hello1Response * SOAP_FMAC4 soap_in__ns3__Hello1Response(struct soap*, const char*, struct _ns3__Hello1Response *, const char*);

#define soap_write__ns3__Hello1Response(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns3__Hello1Response(soap, data), 0) || soap_put__ns3__Hello1Response(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__Hello1Response(struct soap*, const struct _ns3__Hello1Response *, const char*, const char*);

#define soap_read__ns3__Hello1Response(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__Hello1Response(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Hello1Response * SOAP_FMAC4 soap_get__ns3__Hello1Response(struct soap*, struct _ns3__Hello1Response *, const char*, const char*);

#ifndef SOAP_TYPE__ns3__Hello1
#define SOAP_TYPE__ns3__Hello1 (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__Hello1(struct soap*, struct _ns3__Hello1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__Hello1(struct soap*, const struct _ns3__Hello1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__Hello1(struct soap*, const char*, int, const struct _ns3__Hello1 *, const char*);
SOAP_FMAC3 struct _ns3__Hello1 * SOAP_FMAC4 soap_in__ns3__Hello1(struct soap*, const char*, struct _ns3__Hello1 *, const char*);

#define soap_write__ns3__Hello1(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns3__Hello1(soap, data), 0) || soap_put__ns3__Hello1(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__Hello1(struct soap*, const struct _ns3__Hello1 *, const char*, const char*);

#define soap_read__ns3__Hello1(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__Hello1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Hello1 * SOAP_FMAC4 soap_get__ns3__Hello1(struct soap*, struct _ns3__Hello1 *, const char*, const char*);

#ifndef SOAP_TYPE__ns3__GetWsProtocolVersion1Response
#define SOAP_TYPE__ns3__GetWsProtocolVersion1Response (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__GetWsProtocolVersion1Response(struct soap*, struct _ns3__GetWsProtocolVersion1Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__GetWsProtocolVersion1Response(struct soap*, const struct _ns3__GetWsProtocolVersion1Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__GetWsProtocolVersion1Response(struct soap*, const char*, int, const struct _ns3__GetWsProtocolVersion1Response *, const char*);
SOAP_FMAC3 struct _ns3__GetWsProtocolVersion1Response * SOAP_FMAC4 soap_in__ns3__GetWsProtocolVersion1Response(struct soap*, const char*, struct _ns3__GetWsProtocolVersion1Response *, const char*);

#define soap_write__ns3__GetWsProtocolVersion1Response(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns3__GetWsProtocolVersion1Response(soap, data), 0) || soap_put__ns3__GetWsProtocolVersion1Response(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__GetWsProtocolVersion1Response(struct soap*, const struct _ns3__GetWsProtocolVersion1Response *, const char*, const char*);

#define soap_read__ns3__GetWsProtocolVersion1Response(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__GetWsProtocolVersion1Response(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__GetWsProtocolVersion1Response * SOAP_FMAC4 soap_get__ns3__GetWsProtocolVersion1Response(struct soap*, struct _ns3__GetWsProtocolVersion1Response *, const char*, const char*);

#ifndef SOAP_TYPE__ns3__GetWsProtocolVersion1
#define SOAP_TYPE__ns3__GetWsProtocolVersion1 (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__GetWsProtocolVersion1(struct soap*, struct _ns3__GetWsProtocolVersion1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__GetWsProtocolVersion1(struct soap*, const struct _ns3__GetWsProtocolVersion1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__GetWsProtocolVersion1(struct soap*, const char*, int, const struct _ns3__GetWsProtocolVersion1 *, const char*);
SOAP_FMAC3 struct _ns3__GetWsProtocolVersion1 * SOAP_FMAC4 soap_in__ns3__GetWsProtocolVersion1(struct soap*, const char*, struct _ns3__GetWsProtocolVersion1 *, const char*);

#define soap_write__ns3__GetWsProtocolVersion1(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns3__GetWsProtocolVersion1(soap, data), 0) || soap_put__ns3__GetWsProtocolVersion1(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__GetWsProtocolVersion1(struct soap*, const struct _ns3__GetWsProtocolVersion1 *, const char*, const char*);

#define soap_read__ns3__GetWsProtocolVersion1(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__GetWsProtocolVersion1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__GetWsProtocolVersion1 * SOAP_FMAC4 soap_get__ns3__GetWsProtocolVersion1(struct soap*, struct _ns3__GetWsProtocolVersion1 *, const char*, const char*);

#ifndef SOAP_TYPE__ns3__Ping1Response
#define SOAP_TYPE__ns3__Ping1Response (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__Ping1Response(struct soap*, struct _ns3__Ping1Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__Ping1Response(struct soap*, const struct _ns3__Ping1Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__Ping1Response(struct soap*, const char*, int, const struct _ns3__Ping1Response *, const char*);
SOAP_FMAC3 struct _ns3__Ping1Response * SOAP_FMAC4 soap_in__ns3__Ping1Response(struct soap*, const char*, struct _ns3__Ping1Response *, const char*);

#define soap_write__ns3__Ping1Response(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns3__Ping1Response(soap, data), 0) || soap_put__ns3__Ping1Response(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__Ping1Response(struct soap*, const struct _ns3__Ping1Response *, const char*, const char*);

#define soap_read__ns3__Ping1Response(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__Ping1Response(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Ping1Response * SOAP_FMAC4 soap_get__ns3__Ping1Response(struct soap*, struct _ns3__Ping1Response *, const char*, const char*);

#ifndef SOAP_TYPE__ns3__Ping1
#define SOAP_TYPE__ns3__Ping1 (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns3__Ping1(struct soap*, struct _ns3__Ping1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns3__Ping1(struct soap*, const struct _ns3__Ping1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns3__Ping1(struct soap*, const char*, int, const struct _ns3__Ping1 *, const char*);
SOAP_FMAC3 struct _ns3__Ping1 * SOAP_FMAC4 soap_in__ns3__Ping1(struct soap*, const char*, struct _ns3__Ping1 *, const char*);

#define soap_write__ns3__Ping1(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns3__Ping1(soap, data), 0) || soap_put__ns3__Ping1(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns3__Ping1(struct soap*, const struct _ns3__Ping1 *, const char*, const char*);

#define soap_read__ns3__Ping1(soap, data) ( soap_begin_recv(soap) || !soap_get__ns3__Ping1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Ping1 * SOAP_FMAC4 soap_get__ns3__Ping1(struct soap*, struct _ns3__Ping1 *, const char*, const char*);

#ifndef SOAP_TYPE_ns3__Fault1
#define SOAP_TYPE_ns3__Fault1 (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__Fault1(struct soap*, struct ns3__Fault1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__Fault1(struct soap*, const struct ns3__Fault1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__Fault1(struct soap*, const char*, int, const struct ns3__Fault1 *, const char*);
SOAP_FMAC3 struct ns3__Fault1 * SOAP_FMAC4 soap_in_ns3__Fault1(struct soap*, const char*, struct ns3__Fault1 *, const char*);

#define soap_write_ns3__Fault1(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns3__Fault1(soap, data), 0) || soap_put_ns3__Fault1(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__Fault1(struct soap*, const struct ns3__Fault1 *, const char*, const char*);

#define soap_read_ns3__Fault1(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__Fault1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct ns3__Fault1 * SOAP_FMAC4 soap_get_ns3__Fault1(struct soap*, struct ns3__Fault1 *, const char*, const char*);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__base64Binary(struct soap*, struct xsd__base64Binary *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const struct xsd__base64Binary *, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary *, const char*);

#define soap_write_xsd__base64Binary(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__base64Binary(soap, data), 0) || soap_put_xsd__base64Binary(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__base64Binary(struct soap*, const struct xsd__base64Binary *, const char*, const char*);

#define soap_read_xsd__base64Binary(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__base64Binary(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns3__Control1Response
#define SOAP_TYPE_PointerTo_ns3__Control1Response (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__Control1Response(struct soap*, struct _ns3__Control1Response *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__Control1Response(struct soap*, const char *, int, struct _ns3__Control1Response *const*, const char *);
SOAP_FMAC3 struct _ns3__Control1Response ** SOAP_FMAC4 soap_in_PointerTo_ns3__Control1Response(struct soap*, const char*, struct _ns3__Control1Response **, const char*);

#define soap_write_PointerTo_ns3__Control1Response(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__Control1Response(soap, data), 0) || soap_put_PointerTo_ns3__Control1Response(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__Control1Response(struct soap*, struct _ns3__Control1Response *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__Control1Response(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__Control1Response(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Control1Response ** SOAP_FMAC4 soap_get_PointerTo_ns3__Control1Response(struct soap*, struct _ns3__Control1Response **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__Control1
#define SOAP_TYPE_PointerTo_ns3__Control1 (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__Control1(struct soap*, struct _ns3__Control1 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__Control1(struct soap*, const char *, int, struct _ns3__Control1 *const*, const char *);
SOAP_FMAC3 struct _ns3__Control1 ** SOAP_FMAC4 soap_in_PointerTo_ns3__Control1(struct soap*, const char*, struct _ns3__Control1 **, const char*);

#define soap_write_PointerTo_ns3__Control1(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__Control1(soap, data), 0) || soap_put_PointerTo_ns3__Control1(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__Control1(struct soap*, struct _ns3__Control1 *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__Control1(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__Control1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Control1 ** SOAP_FMAC4 soap_get_PointerTo_ns3__Control1(struct soap*, struct _ns3__Control1 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__Echo1Response
#define SOAP_TYPE_PointerTo_ns3__Echo1Response (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__Echo1Response(struct soap*, struct _ns3__Echo1Response *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__Echo1Response(struct soap*, const char *, int, struct _ns3__Echo1Response *const*, const char *);
SOAP_FMAC3 struct _ns3__Echo1Response ** SOAP_FMAC4 soap_in_PointerTo_ns3__Echo1Response(struct soap*, const char*, struct _ns3__Echo1Response **, const char*);

#define soap_write_PointerTo_ns3__Echo1Response(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__Echo1Response(soap, data), 0) || soap_put_PointerTo_ns3__Echo1Response(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__Echo1Response(struct soap*, struct _ns3__Echo1Response *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__Echo1Response(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__Echo1Response(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Echo1Response ** SOAP_FMAC4 soap_get_PointerTo_ns3__Echo1Response(struct soap*, struct _ns3__Echo1Response **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__Echo1
#define SOAP_TYPE_PointerTo_ns3__Echo1 (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__Echo1(struct soap*, struct _ns3__Echo1 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__Echo1(struct soap*, const char *, int, struct _ns3__Echo1 *const*, const char *);
SOAP_FMAC3 struct _ns3__Echo1 ** SOAP_FMAC4 soap_in_PointerTo_ns3__Echo1(struct soap*, const char*, struct _ns3__Echo1 **, const char*);

#define soap_write_PointerTo_ns3__Echo1(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__Echo1(soap, data), 0) || soap_put_PointerTo_ns3__Echo1(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__Echo1(struct soap*, struct _ns3__Echo1 *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__Echo1(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__Echo1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Echo1 ** SOAP_FMAC4 soap_get_PointerTo_ns3__Echo1(struct soap*, struct _ns3__Echo1 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__Hello1Response
#define SOAP_TYPE_PointerTo_ns3__Hello1Response (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__Hello1Response(struct soap*, struct _ns3__Hello1Response *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__Hello1Response(struct soap*, const char *, int, struct _ns3__Hello1Response *const*, const char *);
SOAP_FMAC3 struct _ns3__Hello1Response ** SOAP_FMAC4 soap_in_PointerTo_ns3__Hello1Response(struct soap*, const char*, struct _ns3__Hello1Response **, const char*);

#define soap_write_PointerTo_ns3__Hello1Response(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__Hello1Response(soap, data), 0) || soap_put_PointerTo_ns3__Hello1Response(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__Hello1Response(struct soap*, struct _ns3__Hello1Response *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__Hello1Response(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__Hello1Response(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Hello1Response ** SOAP_FMAC4 soap_get_PointerTo_ns3__Hello1Response(struct soap*, struct _ns3__Hello1Response **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__Hello1
#define SOAP_TYPE_PointerTo_ns3__Hello1 (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__Hello1(struct soap*, struct _ns3__Hello1 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__Hello1(struct soap*, const char *, int, struct _ns3__Hello1 *const*, const char *);
SOAP_FMAC3 struct _ns3__Hello1 ** SOAP_FMAC4 soap_in_PointerTo_ns3__Hello1(struct soap*, const char*, struct _ns3__Hello1 **, const char*);

#define soap_write_PointerTo_ns3__Hello1(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__Hello1(soap, data), 0) || soap_put_PointerTo_ns3__Hello1(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__Hello1(struct soap*, struct _ns3__Hello1 *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__Hello1(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__Hello1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Hello1 ** SOAP_FMAC4 soap_get_PointerTo_ns3__Hello1(struct soap*, struct _ns3__Hello1 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__GetWsProtocolVersion1Response
#define SOAP_TYPE_PointerTo_ns3__GetWsProtocolVersion1Response (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__GetWsProtocolVersion1Response(struct soap*, struct _ns3__GetWsProtocolVersion1Response *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__GetWsProtocolVersion1Response(struct soap*, const char *, int, struct _ns3__GetWsProtocolVersion1Response *const*, const char *);
SOAP_FMAC3 struct _ns3__GetWsProtocolVersion1Response ** SOAP_FMAC4 soap_in_PointerTo_ns3__GetWsProtocolVersion1Response(struct soap*, const char*, struct _ns3__GetWsProtocolVersion1Response **, const char*);

#define soap_write_PointerTo_ns3__GetWsProtocolVersion1Response(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__GetWsProtocolVersion1Response(soap, data), 0) || soap_put_PointerTo_ns3__GetWsProtocolVersion1Response(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__GetWsProtocolVersion1Response(struct soap*, struct _ns3__GetWsProtocolVersion1Response *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__GetWsProtocolVersion1Response(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__GetWsProtocolVersion1Response(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__GetWsProtocolVersion1Response ** SOAP_FMAC4 soap_get_PointerTo_ns3__GetWsProtocolVersion1Response(struct soap*, struct _ns3__GetWsProtocolVersion1Response **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__GetWsProtocolVersion1
#define SOAP_TYPE_PointerTo_ns3__GetWsProtocolVersion1 (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__GetWsProtocolVersion1(struct soap*, struct _ns3__GetWsProtocolVersion1 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__GetWsProtocolVersion1(struct soap*, const char *, int, struct _ns3__GetWsProtocolVersion1 *const*, const char *);
SOAP_FMAC3 struct _ns3__GetWsProtocolVersion1 ** SOAP_FMAC4 soap_in_PointerTo_ns3__GetWsProtocolVersion1(struct soap*, const char*, struct _ns3__GetWsProtocolVersion1 **, const char*);

#define soap_write_PointerTo_ns3__GetWsProtocolVersion1(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__GetWsProtocolVersion1(soap, data), 0) || soap_put_PointerTo_ns3__GetWsProtocolVersion1(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__GetWsProtocolVersion1(struct soap*, struct _ns3__GetWsProtocolVersion1 *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__GetWsProtocolVersion1(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__GetWsProtocolVersion1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__GetWsProtocolVersion1 ** SOAP_FMAC4 soap_get_PointerTo_ns3__GetWsProtocolVersion1(struct soap*, struct _ns3__GetWsProtocolVersion1 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__Ping1Response
#define SOAP_TYPE_PointerTo_ns3__Ping1Response (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__Ping1Response(struct soap*, struct _ns3__Ping1Response *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__Ping1Response(struct soap*, const char *, int, struct _ns3__Ping1Response *const*, const char *);
SOAP_FMAC3 struct _ns3__Ping1Response ** SOAP_FMAC4 soap_in_PointerTo_ns3__Ping1Response(struct soap*, const char*, struct _ns3__Ping1Response **, const char*);

#define soap_write_PointerTo_ns3__Ping1Response(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__Ping1Response(soap, data), 0) || soap_put_PointerTo_ns3__Ping1Response(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__Ping1Response(struct soap*, struct _ns3__Ping1Response *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__Ping1Response(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__Ping1Response(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Ping1Response ** SOAP_FMAC4 soap_get_PointerTo_ns3__Ping1Response(struct soap*, struct _ns3__Ping1Response **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns3__Ping1
#define SOAP_TYPE_PointerTo_ns3__Ping1 (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns3__Ping1(struct soap*, struct _ns3__Ping1 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns3__Ping1(struct soap*, const char *, int, struct _ns3__Ping1 *const*, const char *);
SOAP_FMAC3 struct _ns3__Ping1 ** SOAP_FMAC4 soap_in_PointerTo_ns3__Ping1(struct soap*, const char*, struct _ns3__Ping1 **, const char*);

#define soap_write_PointerTo_ns3__Ping1(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns3__Ping1(soap, data), 0) || soap_put_PointerTo_ns3__Ping1(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns3__Ping1(struct soap*, struct _ns3__Ping1 *const*, const char*, const char*);

#define soap_read_PointerTo_ns3__Ping1(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns3__Ping1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct _ns3__Ping1 ** SOAP_FMAC4 soap_get_PointerTo_ns3__Ping1(struct soap*, struct _ns3__Ping1 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons3__FaultType1
#define SOAP_TYPE_PointerTons3__FaultType1 (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__FaultType1(struct soap*, enum ns3__FaultType1 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__FaultType1(struct soap*, const char *, int, enum ns3__FaultType1 *const*, const char *);
SOAP_FMAC3 enum ns3__FaultType1 ** SOAP_FMAC4 soap_in_PointerTons3__FaultType1(struct soap*, const char*, enum ns3__FaultType1 **, const char*);

#define soap_write_PointerTons3__FaultType1(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons3__FaultType1(soap, data), 0) || soap_put_PointerTons3__FaultType1(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__FaultType1(struct soap*, enum ns3__FaultType1 *const*, const char*, const char*);

#define soap_read_PointerTons3__FaultType1(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__FaultType1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 enum ns3__FaultType1 ** SOAP_FMAC4 soap_get_PointerTons3__FaultType1(struct soap*, enum ns3__FaultType1 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons3__Fault1
#define SOAP_TYPE_PointerTons3__Fault1 (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__Fault1(struct soap*, struct ns3__Fault1 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__Fault1(struct soap*, const char *, int, struct ns3__Fault1 *const*, const char *);
SOAP_FMAC3 struct ns3__Fault1 ** SOAP_FMAC4 soap_in_PointerTons3__Fault1(struct soap*, const char*, struct ns3__Fault1 **, const char*);

#define soap_write_PointerTons3__Fault1(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons3__Fault1(soap, data), 0) || soap_put_PointerTons3__Fault1(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__Fault1(struct soap*, struct ns3__Fault1 *const*, const char*, const char*);

#define soap_read_PointerTons3__Fault1(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__Fault1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct ns3__Fault1 ** SOAP_FMAC4 soap_get_PointerTons3__Fault1(struct soap*, struct ns3__Fault1 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#define soap_write_PointerToint(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToint(soap, data), 0) || soap_put_PointerToint(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);

#define soap_read_PointerToint(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToint(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);

#ifndef SOAP_TYPE_ns4__guid
#define SOAP_TYPE_ns4__guid (22)
#endif

#define soap_default_ns4__guid(soap, a) soap_default_string(soap, a)


#define soap_serialize_ns4__guid(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__guid(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_ns4__guid(struct soap*, const char*, char **, const char*);

#define soap_write_ns4__guid(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns4__guid(soap, data), 0) || soap_put_ns4__guid(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__guid(struct soap*, char *const*, const char*, const char*);

#define soap_read_ns4__guid(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__guid(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_ns4__guid(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_ns4__duration
#define SOAP_TYPE_ns4__duration (21)
#endif

#define soap_default_ns4__duration(soap, a) soap_default_string(soap, a)


#define soap_serialize_ns4__duration(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__duration(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_ns4__duration(struct soap*, const char*, char **, const char*);

#define soap_write_ns4__duration(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns4__duration(soap, data), 0) || soap_put_ns4__duration(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__duration(struct soap*, char *const*, const char*, const char*);

#define soap_read_ns4__duration(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__duration(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_ns4__duration(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__duration
#define SOAP_TYPE_xsd__duration (17)
#endif

#define soap_default_xsd__duration(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__duration(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__duration(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__duration(struct soap*, const char*, char **, const char*);

#define soap_write_xsd__duration(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__duration(soap, data), 0) || soap_put_xsd__duration(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__duration(struct soap*, char *const*, const char*, const char*);

#define soap_read_xsd__duration(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__duration(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__duration(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (16)
#endif

#define soap_default_xsd__decimal(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__decimal(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__decimal(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__decimal(struct soap*, const char*, char **, const char*);

#define soap_write_xsd__decimal(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__decimal(soap, data), 0) || soap_put_xsd__decimal(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__decimal(struct soap*, char *const*, const char*, const char*);

#define soap_read_xsd__decimal(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__decimal(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__decimal(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#define soap_write_PointerTounsignedByte(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTounsignedByte(soap, data), 0) || soap_put_PointerTounsignedByte(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);

#define soap_read_PointerTounsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTounsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (9)
#endif

#define soap_default_xsd__anyURI(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__anyURI(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);

#define soap_write_xsd__anyURI(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__anyURI(soap, data), 0) || soap_put_xsd__anyURI(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char *const*, const char*, const char*);

#define soap_read_xsd__anyURI(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__anyURI(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__IDREF
#define SOAP_TYPE_xsd__IDREF (8)
#endif

#define soap_default_xsd__IDREF(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__IDREF(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__IDREF(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__IDREF(struct soap*, const char*, char **, const char*);

#define soap_write_xsd__IDREF(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__IDREF(soap, data), 0) || soap_put_xsd__IDREF(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__IDREF(struct soap*, char *const*, const char*, const char*);

#define soap_read_xsd__IDREF(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__IDREF(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__IDREF(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__ID
#define SOAP_TYPE_xsd__ID (7)
#endif

#define soap_default_xsd__ID(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__ID(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__ID(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__ID(struct soap*, const char*, char **, const char*);

#define soap_write_xsd__ID(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__ID(soap, data), 0) || soap_put_xsd__ID(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__ID(struct soap*, char *const*, const char*, const char*);

#define soap_read_xsd__ID(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__ID(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__ID(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of webservices_devicewebserviceH.h */
