/* webservices_devicewebserviceClientLib.c
   Generated by gSOAP 2.7.15 from webservices_devicewebservice.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

/** Use this file in your project build instead of the two files webservices_devicewebserviceC.c and webservices_devicewebserviceClient.c. This hides the serializer functions and avoids linking problems when linking multiple clients and servers. */

#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#define SOAP_FMAC3 static
#include "webservices_devicewebserviceC.c"
#include "webservices_devicewebserviceClient.c"

/* End of webservices_devicewebserviceClientLib.c */
