/* core-common-manifest.c : UpdateTV Core Component Manifest Management Code

   Copyright (c) 2009-2011 UpdateLogic Incorporated. All rights reserved.

   Contains the following UpdateTV Agent Personality Map Entry Points
   ------------------------------------------------------------------

   ------------------------------------------------------------------
 
   The Agent ships with a manifest component directory file which is encrypted and generated by Publisher.
   The manifest file is referenced by an entry in the s_aStoreEntries array in platform-store-file.c.
   The Agent integrator should place the manifest file anywhere in their file system that is writeable.
   The manifest file needs to be in a writeable partition because it is replaced by the component directory
   of an update.

   Revision History (newest edits added to the top)

   Who             Date        Edit
   Bob Taylor      06/27/2011  Removed recovery logic.
   Bob Taylor      06/04/2011  Added UTV_MANIFEST_OPEN_RETRY_COUNT and UTV_MANIFEST_OPEN_FAILS error.
   Bob Taylor      04/28/2011  Added UtvManifestOptional() function.
   Nathan Ford     02/21/2011  Modified UtvManifestCommit() to store encrypted manifest held with the image instead of relying on
                               update-0.store
   Bob Taylor      10/01/2010  Invalidate UQ cache when component manifest isn't found and is copied from backup.
   Jim Muchow      09/21/2010  BE support.
   Bob Taylor      06/22/2010  Loop test support.  Fixed factory mode fallback return value.
   Bob Taylor      06/16/2010  Removed ifndef UTV_DEBUG direct model group in UtvManifestGetModelGroup().
   Bob Taylor      05/07/2010  Fixed manifest retry bug that was reporting error when there was none.
   Bob Taylor      04/30/2010  Added delete/retry to recover from bad component manifest.
   Bob Taylor      04/15/2010  Converted query host string to string table.
   Bob Taylor      04/13/2010  Added set of download ended type to unknown for new manifest trigger.
   Bob Taylor      04/08/2010  Added trigger to cause Agent to send MV to NOC when new component manifest is installed.
   Bob Taylor      02/09/2010  Added UtvPlatformGetActiveCompManifestName() and UtvPlatformGetBackupCompManifestName().
   Bob Taylor      11/17/2009  Added manifest copy to UtvManifestOpen().
                               Added UtvManifestGetQueryHost().
                               Changed manifest commit close logic.
   Bob Taylor      07/20/2009  UtvManifestGetModelGroup() added.
   Bob Taylor      03/06/2009  Created.
*/

#include "utv.h"

static UTV_BOOL s_bManifestOpen = UTV_FALSE;
UTV_UINT32 g_hManifestImage = UTV_CORE_IMAGE_INVALID;
static UTV_INT8 s_szCachedQueryHost[ UTV_MAX_QUERY_HOST_LEN ] = { 0 };

UTV_RESULT UtvManifestOpen( void )
{
    UTV_RESULT              rStatus, lStatus;
    UtvImageAccessInterface utvIAI;

    /* if we're already open then there's nothing to do */
    if ( s_bManifestOpen )
        return UTV_OK;

	/* if the active component manifest can't be found in the persistent directory then copy
	   it from backup read-only memory */
	if ( !UtvPlatformFilePathExists( UtvPlatformGetActiveCompManifestName() ) )
	{
		/* set the unreported MV to a value that indicates we should send the current MV when the network connects. */
		g_utvAgentPersistentStorage.utvDiagStats.usLastDownloadEndedUnreportedMV = (UTV_UINT16) UTV_CORE_IMAGE_INVALID;	

		/* invalidate the UQ cache so that we check for a download when this happens */
		UtvInternetOverrideValidQueryResponseCached( UTV_FALSE );

		UtvMessage( UTV_LEVEL_INFO, "MANIFEST COPY FROM %s TO %s", 
					UtvPlatformGetBackupCompManifestName(), UtvPlatformGetActiveCompManifestName() );
		if ( UTV_OK != ( rStatus = UtvPlatformFileCopy( UtvPlatformGetBackupCompManifestName(), 
														UtvPlatformGetActiveCompManifestName() )))
		{
			UtvLogEvent( UTV_LEVEL_ERROR, UTV_CAT_MANIFEST, rStatus, __LINE__ );
			return rStatus;
		}
	}
    
	/* otherwise open up the manifest store entry */
	/* get the file version of the image access interface */
	if ( UTV_OK != ( rStatus = UtvFileImageAccessInterfaceGet( &utvIAI )))
	{
		UtvMessage( UTV_LEVEL_ERROR, 
					"UtvFileImageAccessInterfaceGet() fails with error \"%s\"", 
					UtvGetMessageString( rStatus ) );
		return rStatus;
	}

	/* attempt to open this image which will download and decrypt its component directory */
	if ( UTV_OK != ( rStatus = UtvImageOpen( NULL, (UTV_INT8 *)UTV_PLATFORM_UPDATE_MANIFEST_INDEX, &utvIAI, 
											 &g_hManifestImage, UTV_PLATFORM_UPDATE_STORE_INVALID )))
	{
		/* if the open didn't work for some reason then try to delete the file */
		if ( UTV_OK != ( lStatus = UtvPlatformFileDelete( UtvPlatformGetActiveCompManifestName() )))
		{
			UtvLogEvent( UTV_LEVEL_ERROR, UTV_CAT_MANIFEST, lStatus, __LINE__ );
		}

        UtvLogEvent( UTV_LEVEL_ERROR, UTV_CAT_MANIFEST, rStatus, __LINE__ );
		return rStatus;
    }

    if ( UTV_OK != ( rStatus = UtvImageCheckFileLocks( g_hManifestImage )))
    {
        UtvLogEvent( UTV_LEVEL_ERROR, UTV_CAT_MANIFEST, rStatus, __LINE__ );
        UtvImageClose( g_hManifestImage );
        return rStatus;
    }
    
    s_bManifestOpen = UTV_TRUE;
    return UTV_OK;
}

UTV_RESULT UtvManifestClose( void )
{
    UTV_RESULT              rStatus;

    /* if we're already closed then there's nothing to do */
    if ( !s_bManifestOpen )
        return UTV_OK;

    /* attempt to open this image which will download and decrypt its component directory */
    if ( UTV_OK != ( rStatus = UtvImageClose( g_hManifestImage )))
    {
        UtvMessage( UTV_LEVEL_WARN, "UtvImageClose(): \"%s\"", UtvGetMessageString( rStatus ) );
    }

    s_bManifestOpen = UTV_FALSE;
    return UTV_OK;
}

UTV_UINT16 UtvManifestGetModelGroup( void )
{
    /* In debug mode return the model group from the component manifest to allow snap-on model groups */

    UTV_RESULT      rStatus;
    UtvCompDirHdr  *pCompDirHdr;
    UtvRange       *pHWMRanges;
    UtvRange       *pSWVRanges;
    UtvDependency  *pSWVDeps;
    UtvTextDef     *pTextDefs;

    if ( UTV_OK != UtvManifestOpen())
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestGetModelGroup() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_MODEL_GROUP );
        return UTV_PLATFORM_FALLBACK_MODEL_GROUP;
    }

    if ( UTV_OK != ( rStatus = UtvImageGetCompDirHdr( g_hManifestImage, &pCompDirHdr, &pHWMRanges, &pSWVRanges,
                                                      &pSWVDeps, &pTextDefs )))
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvImageGetCompDirHdr(): \"%s\"", UtvGetMessageString( rStatus ) );
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestGetModelGroup() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_MODEL_GROUP );
        return UTV_PLATFORM_FALLBACK_MODEL_GROUP;
    }

    return Utv_16letoh( pCompDirHdr->usPlatformModelGroup );
}

UTV_UINT16 UtvManifestGetSoftwareVersion( void )
{
    UTV_RESULT      rStatus;
    UtvCompDirHdr  *pCompDirHdr;
    UtvRange       *pHWMRanges;
    UtvRange       *pSWVRanges;
    UtvDependency  *pSWVDeps;
    UtvTextDef     *pTextDefs;

    if ( UTV_OK != UtvManifestOpen())
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestGetSoftwareVersion() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_SW_VER );
        return UTV_PLATFORM_FALLBACK_SW_VER;
    }

    if ( UTV_OK != ( rStatus = UtvImageGetCompDirHdr( g_hManifestImage, &pCompDirHdr, &pHWMRanges, &pSWVRanges,
                                                      &pSWVDeps, &pTextDefs )))
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvImageGetCompDirHdr(): \"%s\"", UtvGetMessageString( rStatus ) );
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestGetSoftwareVersion() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_SW_VER );
        return UTV_PLATFORM_FALLBACK_SW_VER;
    }

    return Utv_16letoh( pCompDirHdr->usUpdateSoftwareVersion );

}

UTV_UINT16 UtvManifestGetModuleVersion( void )
{
    UTV_RESULT      rStatus;
    UtvCompDirHdr  *pCompDirHdr;
    UtvRange       *pHWMRanges;
    UtvRange       *pSWVRanges;
    UtvDependency  *pSWVDeps;
    UtvTextDef     *pTextDefs;

    if ( UTV_OK != UtvManifestOpen())
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestGetModuleVersion() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_MOD_VER );
        return UTV_PLATFORM_FALLBACK_MOD_VER;
    }

    if ( UTV_OK != ( rStatus = UtvImageGetCompDirHdr( g_hManifestImage, &pCompDirHdr, &pHWMRanges, &pSWVRanges,
                                                      &pSWVDeps, &pTextDefs )))
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvImageGetCompDirHdr(): \"%s\"", UtvGetMessageString( rStatus ) );
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestGetModuleVersion() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_MOD_VER );
        return UTV_PLATFORM_FALLBACK_MOD_VER;
    }

    return Utv_16letoh( pCompDirHdr->usUpdateModuleVersion );

}

UTV_BOOL UtvManifestGetFieldTestStatus( void )
{
    UTV_RESULT      rStatus;
    UtvCompDirHdr  *pCompDirHdr;
    UtvRange       *pHWMRanges;
    UtvRange       *pSWVRanges;
    UtvDependency  *pSWVDeps;
    UtvTextDef     *pTextDefs;

    if ( UTV_OK != UtvManifestOpen())
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestGetFieldTestStatus() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_FTEST );
        return UTV_PLATFORM_FALLBACK_FTEST;
    }

    if ( UTV_OK != ( rStatus = UtvImageGetCompDirHdr( g_hManifestImage, &pCompDirHdr, &pHWMRanges, &pSWVRanges,
                                                      &pSWVDeps, &pTextDefs )))
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvImageGetCompDirHdr(): \"%s\"", UtvGetMessageString( rStatus ) );
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestGetFieldTestStatus() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_FTEST );
        return UTV_PLATFORM_FALLBACK_FTEST;
    }

    return 0 != ( Utv_32letoh( pCompDirHdr->uiUpdateAttributes ) & UTV_COMPONENT_ATTR_FTEST );
}

UTV_BOOL UtvManifestGetFactoryTestStatus( void )
{
    UTV_RESULT      rStatus;
    UtvCompDirHdr  *pCompDirHdr;
    UtvRange       *pHWMRanges;
    UtvRange       *pSWVRanges;
    UtvDependency  *pSWVDeps;
    UtvTextDef     *pTextDefs;
    UTV_BOOL        bResult;

    if ( UTV_OK != UtvManifestOpen())
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestGetFactoryTestStatus() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_FACT_TEST );
        return UTV_PLATFORM_FALLBACK_FACT_TEST;
    }

    if ( UTV_OK != ( rStatus = UtvImageGetCompDirHdr( g_hManifestImage, &pCompDirHdr, &pHWMRanges, &pSWVRanges,
                                                      &pSWVDeps, &pTextDefs )))
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvImageGetCompDirHdr(): \"%s\"", UtvGetMessageString( rStatus ) );
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestGetFactoryTestStatus() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_FACT_TEST );
        return UTV_PLATFORM_FALLBACK_FACT_TEST;
    }

    
    bResult = ( 0 != ( Utv_32letoh( pCompDirHdr->uiUpdateAttributes ) & UTV_COMPONENT_ATTR_FACT_TEST ));
    
    /* call platform specific notification method to inform operator of factory mode */
    UtvPlatformFactoryModeNotice( bResult );

    return bResult;
}

UTV_BOOL UtvManifestGetLoopTestStatus( void )
{
    UTV_RESULT      rStatus;
    UtvCompDirHdr  *pCompDirHdr;
    UtvRange       *pHWMRanges;
    UtvRange       *pSWVRanges;
    UtvDependency  *pSWVDeps;
    UtvTextDef     *pTextDefs;
    UTV_BOOL        bResult;

    if ( UTV_OK != UtvManifestOpen())
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestGetLoopTestStatus() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_LOOP_TEST );
        return UTV_PLATFORM_FALLBACK_LOOP_TEST;
    }

    if ( UTV_OK != ( rStatus = UtvImageGetCompDirHdr( g_hManifestImage, &pCompDirHdr, &pHWMRanges, &pSWVRanges,
                                                      &pSWVDeps, &pTextDefs )))
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvImageGetCompDirHdr(): \"%s\"", UtvGetMessageString( rStatus ) );
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestGetLoopTestStatus() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_LOOP_TEST );
        return UTV_PLATFORM_FALLBACK_LOOP_TEST;
    }

    
    bResult = ( 0 != ( Utv_32letoh( pCompDirHdr->uiUpdateAttributes ) & UTV_COMPONENT_ATTR_LOOP_TEST ));
    
    return bResult;
}

UTV_BOOL UtvManifestAllowAdditions( void )
{
    UTV_RESULT      rStatus;
    UtvCompDirHdr  *pCompDirHdr;
    UtvRange       *pHWMRanges;
    UtvRange       *pSWVRanges;
    UtvDependency  *pSWVDeps;
    UtvTextDef     *pTextDefs;

    if ( UTV_OK != UtvManifestOpen())
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestAllowAdditions() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_ALLOW_ADDS );
        return UTV_PLATFORM_FALLBACK_ALLOW_ADDS;
    }

    if ( UTV_OK != ( rStatus = UtvImageGetCompDirHdr( g_hManifestImage, &pCompDirHdr, &pHWMRanges, &pSWVRanges,
                                                      &pSWVDeps, &pTextDefs )))
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvImageGetCompDirHdr(): \"%s\"", UtvGetMessageString( rStatus ) );
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestAllowAdditions() FALLING BACK to: %d", UTV_PLATFORM_FALLBACK_ALLOW_ADDS );
        return UTV_PLATFORM_FALLBACK_ALLOW_ADDS;
    }

    return 0 == ( Utv_32letoh( pCompDirHdr->uiUpdateAttributes ) & UTV_COMPONENT_ATTR_NO_ADDS);
}

UTV_BOOL UtvManifestOptional( UTV_UINT32 uiImage )
{
    UTV_RESULT      rStatus;
    UtvCompDirHdr  *pCompDirHdr;
    UtvRange       *pHWMRanges;
    UtvRange       *pSWVRanges;
    UtvDependency  *pSWVDeps;
    UtvTextDef     *pTextDefs;

    if ( UTV_OK != ( rStatus = UtvImageGetCompDirHdr( uiImage, &pCompDirHdr, &pHWMRanges, &pSWVRanges,
                                                      &pSWVDeps, &pTextDefs )))
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvImageGetCompDirHdr(): \"%s\"", UtvGetMessageString( rStatus ) );
        UtvMessage( UTV_LEVEL_ERROR, "UtvManifestOptional() FALLING BACK to false" );
        return UTV_FALSE;
    }

    return 0 != ( Utv_32letoh( pCompDirHdr->uiUpdateAttributes ) & UTV_COMPONENT_ATTR_OPTIONAL);
}

UTV_INT8 *UtvManifestGetQueryHost( void )
{
    UTV_RESULT      rStatus;
    UTV_INT8       *pszTextDef;

    if ( 0 != s_szCachedQueryHost[ 0 ] )
        return s_szCachedQueryHost;

    do
    {
        if ( UTV_OK != (rStatus = UtvManifestOpen()))
        {
            UtvMessage( UTV_LEVEL_ERROR, "UtvManifestOpen(): \"%s\"", UtvGetMessageString( rStatus ) );
            break;
        }
        
        if ( UTV_OK != (rStatus = UtvPublicImageGetUpdateTextDef( g_hManifestImage, UtvStringsLookup( UTV_QUERY_HOST ), &pszTextDef )))
        {
            UtvMessage( UTV_LEVEL_ERROR, "UtvPublicImageGetUpdateTextDef( old publisher? ): \"%s\"", UtvGetMessageString( rStatus ) );
            break;
        }

        UtvStrnCopy( (UTV_BYTE *) s_szCachedQueryHost, sizeof( s_szCachedQueryHost ), 
                     (UTV_BYTE *) pszTextDef, UtvStrlen( (UTV_BYTE *) pszTextDef ));
        UtvMessage( UTV_LEVEL_INFO, "Setting cached query host to: \"%s\"", s_szCachedQueryHost );
        return s_szCachedQueryHost;

    } while( UTV_FALSE );

    UtvMessage( UTV_LEVEL_ERROR, "UtvManifestGetQueryHost() FALLING BACK to: %s", UTV_PLATFORM_FALLBACK_QUERY_HOST );
    return UTV_PLATFORM_FALLBACK_QUERY_HOST;
}

UTV_RESULT UtvManifestCommit( UTV_UINT32 hImage )
{
    UTV_RESULT                     rStatus;
    UTV_UINT32               uiCompDirSize, uiBytesWritten;
    UTV_BYTE                *pCompDir;
    UtvImageAccessInterface        utvIAI;
    UTV_UINT32               hStore;

    UtvMessage( UTV_LEVEL_INFO, "MANIFEST COMMIT start" );

    /* get the file version of the image access interface */
    if ( UTV_OK != ( rStatus = UtvFileImageAccessInterfaceGet( &utvIAI )))
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvFileImageAccessInterfaceGet( commit ) fails with error \"%s\"", UtvGetMessageString( rStatus ) );
        return rStatus;
    }

    /* Get a pointer to and size of the encrypted component manifest */
    if ( UTV_OK != ( rStatus = UtvImageGetEncryptedCompDir( hImage, &pCompDir, &uiCompDirSize )))
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvImageGetEncryptedCompDir() fails with error \"%s\"", UtvGetMessageString( rStatus ) );
        return rStatus;
    }

    /* Open the component manifest store */
    if ( UTV_OK != ( rStatus = UtvPlatformStoreOpen( UTV_PLATFORM_UPDATE_MANIFEST_INDEX,
                                                     UTV_PLATFORM_UPDATE_STORE_FLAG_WRITE | 
                                                       UTV_PLATFORM_UPDATE_STORE_FLAG_OVERWRITE,
                                                     UTV_MAX_COMP_DIR_SIZE,
                                                    &hStore,
                                                     NULL,
                                                     NULL )))
    {
        UtvMessage( UTV_LEVEL_ERROR, "UtvPlatformStoreOpen( UTV_PLATFORM_UPDATE_MANIFEST_INDEX ) fails with error \"%s\"", UtvGetMessageString( rStatus ) );
        return rStatus;
    }

    /* write to the store */
    if ( UTV_OK != ( rStatus = UtvPlatformStoreWrite( UTV_PLATFORM_UPDATE_MANIFEST_INDEX, pCompDir,
                                                              Utv_32letoh( uiCompDirSize ), &uiBytesWritten )))
    {
         UtvMessage( UTV_LEVEL_ERROR, " UtvPlatformStoreWrite( %d, %d ) fails: %s",
                     Utv_32letoh( uiCompDirSize ),
                     uiBytesWritten, UtvGetMessageString( rStatus ) );
        return rStatus;
    }
    
    /* close the aux image which is the manifest in this case. */
    if ( UTV_OK != ( rStatus = UtvPlatformStoreClose( UTV_PLATFORM_UPDATE_MANIFEST_INDEX )))
    {
        UtvLogEvent( UTV_LEVEL_ERROR, UTV_CAT_MANIFEST, rStatus, __LINE__ );
        return rStatus;
    }

    UtvMessage( UTV_LEVEL_INFO, "MANIFEST COMMIT complete" );

    return UTV_OK;
}
